name: Build an Publish to Dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t gurkesalat/skyfactory_5:latest
    - name: push
      run: |
	docker login -u gurkesalat -p ${{secrets.DOCKER_HUB}}
	docker push gurkesalat/skyfactory_5:latest
